import re
import subprocess
from pathlib import Path

import typer

app = typer.Typer()


SUPPORTED_ENGINES = ["sqlite", "postgres", "mysql"]

ENGINE_ALIASES = {
    "postgresql": "postgres",
    "postgres": "postgres",
    "mysql": "mysql",
    "sqlite3": "sqlite",
    "sqlite": "sqlite",
}

ENGINE_PACKAGES = {
    "sqlite": "aiosqlite",
    "postgres": "asyncpg",
    "mysql": "asyncmy",
}


def find_project_root() -> Path | None:
    current = Path.cwd().resolve()

    while True:
        if (current / "main.py").is_file() and (current / "apps").is_dir():
            return current
        if current == current.parent:
            return None
        current = current.parent


def require_project_root() -> Path:
    project_root = find_project_root()

    if project_root is None:
        typer.secho("No Fapix project found.", fg=typer.colors.RED, bold=True)
        typer.echo("Run 'fapix startdb' inside a Fapix project.")
        raise typer.Exit(code=1)

    return project_root


def discover_model_modules(project_root: Path) -> list[str]:
    apps_dir = project_root / "apps"
    modules = []

    if not apps_dir.exists():
        return modules

    for app_dir in sorted(apps_dir.iterdir()):
        if not app_dir.is_dir() or app_dir.name.startswith("_"):
            continue

        if (app_dir / "models.py").is_file():
            modules.append(f"apps.{app_dir.name}.models")

    return modules


def normalize_engine(engine: str) -> str:
    return ENGINE_ALIASES.get(engine.strip().lower(), engine.strip().lower())


def build_database_url(engine: str, db_path: Path, dbname: str) -> str:
    if engine == "sqlite":
        return f"sqlite://{db_path}"

    if engine == "postgres":
        return f"postgres://${{DB_USER}}:${{DB_PASSWORD}}@${{DB_HOST}}:${{DB_PORT}}/{dbname}"

    if engine == "mysql":
        return f"mysql://${{DB_USER}}:${{DB_PASSWORD}}@${{DB_HOST}}:${{DB_PORT}}/{dbname}"

    raise ValueError(f"Unsupported engine: {engine}")


def generate_db_config(config_path: Path, database_url: str, model_modules: list[str]) -> None:
    model_lines = "".join(f'            "{module}",\n' for module in model_modules)

    content = f'''"""Fapix database configuration. Generated by: fapix startdb"""

TORTOISE_ORM = {{
    "connections": {{
        "default": "{database_url}",
    }},
    "apps": {{
        "models": {{
            "models": [
{model_lines}            "aerich.models",
            ],
            "default_connection": "default",
        }},
    }},
}}


async def connect_db() -> None:
    from tortoise import Tortoise

    await Tortoise.init(config=TORTOISE_ORM, _enable_global_fallback=True)


async def disconnect_db() -> None:
    from tortoise import Tortoise

    await Tortoise.close_connections()
'''

    config_path.write_text(content, encoding="utf-8")


def install_dependencies(engine: str) -> None:
    packages = ["tortoise-orm", ENGINE_PACKAGES[engine]]

    typer.echo(f"Installing dependencies: {', '.join(packages)}")

    try:
        subprocess.run(["pip", "install", *packages], check=True)
    except subprocess.CalledProcessError:
        typer.secho("Failed to install database dependencies.", fg=typer.colors.RED)
        raise typer.Exit(code=1)


def _ensure_migrations_dir(root: Path) -> None:
    migrations_dir = root / "migrations"

    if migrations_dir.is_dir():
        return

    migrations_dir.mkdir()
    (migrations_dir / "__init__.py").write_text("", encoding="utf-8")


def _write_aerich_ini(root: Path) -> None:
    ini_file = root / "aerich.ini"

    if ini_file.is_file():
        return

    content = '''[aerich]
tortoise_orm = db_config.TORTOISE_ORM
location = ./migrations
src_folder = .
'''
    ini_file.write_text(content, encoding="utf-8")


def _ensure_aerich_pyproject(root: Path) -> None:
    pyproject_file = root / "pyproject.toml"

    aerich_section = (
        "\n[tool.aerich]\n"
        'tortoise_orm = "db_config.TORTOISE_ORM"\n'
        'location = "./migrations"\n'
        'src_folder = "."\n'
    )

    if not pyproject_file.is_file():
        pyproject_file.write_text(aerich_section.lstrip("\n"), encoding="utf-8")
        return

    content = pyproject_file.read_text(encoding="utf-8")

    if "[tool.aerich]" in content:
        return

    pyproject_file.write_text(content.rstrip() + "\n" + aerich_section, encoding="utf-8")


def _insert_after_last_import(content: str, line_to_insert: str) -> str:
    lines = content.splitlines()

    if line_to_insert in content:
        return content

    last_import_index = -1

    for index, line in enumerate(lines):
        if line.strip().startswith(("import ", "from ")):
            last_import_index = index

    insert_at = last_import_index + 1 if last_import_index >= 0 else 0
    lines.insert(insert_at, line_to_insert)
    return "\n".join(lines)


def wire_db_into_main(project_root: Path) -> None:
    """
    Add the asynccontextmanager import, a lifespan() function wired to
    db_config.connect_db/disconnect_db, and lifespan=lifespan on the
    FastAPI(...) call in main.py. No-ops if main.py is already wired.
    """
    main_file = project_root / "main.py"

    if not main_file.is_file():
        return

    content = main_file.read_text(encoding="utf-8")

    if "async def lifespan(" in content:
        return

    content = _insert_after_last_import(content, "from contextlib import asynccontextmanager")
    content = _insert_after_last_import(content, "from db_config import TORTOISE_ORM, connect_db, disconnect_db")

    lifespan_block = (
        "\n\n@asynccontextmanager\n"
        "async def lifespan(app: FastAPI):\n"
        "    await connect_db()\n"
        "    yield\n"
        "    await disconnect_db()\n\n"
    )

    match = re.search(r"^.*FastAPI\(.*$", content, flags=re.MULTILINE)

    if match is None:
        content = content.rstrip() + lifespan_block
    else:
        content = content[:match.start()] + lifespan_block.lstrip("\n") + content[match.start():]

    if "FastAPI()" in content:
        content = content.replace("FastAPI()", "FastAPI(lifespan=lifespan)", 1)
    elif "lifespan=" not in content:
        content = re.sub(r"FastAPI\(", "FastAPI(lifespan=lifespan, ", content, count=1)

    main_file.write_text(content.rstrip() + "\n", encoding="utf-8")

def _run_aerich_init(project_root: Path) -> None:
    typer.echo("Initializing Aerich...")

    try:
        subprocess.run(
            [sys.executable, "-m", "aerich", "init", "-t", "db_config.TORTOISE_ORM"],
            cwd=project_root,
            check=True,
        )
    except subprocess.CalledProcessError:
        typer.secho("Failed to initialize Aerich.", fg=typer.colors.RED)
        raise typer.Exit(code=1)


def _run_aerich_init_db(project_root: Path) -> None:
    try:
        subprocess.run(
            [sys.executable, "-m", "aerich", "init-db"],
            cwd=project_root,
            check=True,
        )
    except subprocess.CalledProcessError:
        typer.secho("Failed to create initial migration.", fg=typer.colors.RED)
        raise typer.Exit(code=1)


def _ensure_aerich_initialized(project_root: Path) -> None:

    snapshot_marker = project_root / "migrations" / "models"

    if snapshot_marker.exists():
        return

    _run_aerich_init(project_root)
    _run_aerich_init_db(project_root)
@app.command()
def startdb_cmd(
    dbname: str = typer.Option(None, "--dbname", "-d", help="Database name"),
    engine: str = typer.Option(None, "--engine", "-e", help="Database engine (sqlite/postgres/mysql)"),
    app_name: str = typer.Option(None, "--app", "-a", help="App for an app-specific database"),
):
    """Configure the Fapix database connection, global or app-specific."""

    project_root = require_project_root()
    apps_dir = project_root / "apps"

    use_global = not app_name and typer.confirm("Use a single global database?", default=True)

    if use_global:
        database_root = project_root
        config_path = project_root / "db_config.py"
        database_scope = "global"
    else:
        if not app_name:
            app_name = typer.prompt("Enter the app name")

        app_name = app_name.strip().lower().replace(" ", "_")
        app_path = apps_dir / app_name

        if not app_path.is_dir():
            typer.secho(f"App '{app_name}' does not exist.", fg=typer.colors.RED)
            typer.echo(f"Create it first with: fapix startapp {app_name}")
            raise typer.Exit(code=1)

        database_root = app_path
        config_path = app_path / "db_config.py"
        database_scope = f"app: {app_name}"

    if not dbname:
        dbname = typer.prompt("Enter your database name", default="db")

    if not engine:
        engine = typer.prompt("Enter database engine (sqlite/postgres/mysql)", default="sqlite")

    engine = normalize_engine(engine)

    if engine not in SUPPORTED_ENGINES:
        typer.secho(f"Unsupported engine '{engine}'.", fg=typer.colors.RED)
        typer.echo(f"Supported engines: {', '.join(SUPPORTED_ENGINES)}")
        raise typer.Exit(code=1)

    if engine == "sqlite":
        database_file = database_root / f"{dbname}.sqlite3"
        database_url = f"sqlite://{database_file}"
    else:
        database_file = None
        database_url = build_database_url(engine, database_root, dbname)

    model_modules = discover_model_modules(project_root)

    install_dependencies(engine)

    if config_path.exists():
        overwrite = typer.confirm(f"{config_path} already exists. Overwrite it?", default=False)
        if not overwrite:
            typer.secho("Database setup cancelled.", fg=typer.colors.YELLOW)
            raise typer.Exit()

    generate_db_config(config_path, database_url, model_modules)

    if use_global:
        _ensure_migrations_dir(project_root)
        _write_aerich_ini(project_root)
        _ensure_aerich_pyproject(project_root)
        wire_db_into_main(project_root)
    else:
        typer.secho(
            "App-scoped databases are not wired into main.py's lifespan yet; "
            "connect/disconnect this app's connection manually.",
            fg=typer.colors.YELLOW,
        )

    typer.echo()
    typer.secho("Database configuration created.", fg=typer.colors.GREEN, bold=True)
    typer.echo(f"Scope: {database_scope}")
    typer.echo(f"Engine: {engine}")
    typer.echo(f"Database: {dbname}")
    typer.echo(f"Config: {config_path}")

    if database_file:
        typer.echo(f"SQLite file: {database_file}")

    typer.echo()

    if model_modules:
        typer.echo("Registered model modules:")
        for module in model_modules:
            typer.echo(f"  {module}")
    else:
        typer.secho("No app models found yet.", fg=typer.colors.YELLOW)